version: "3.8"

services:
  nextjs-app:
    build:
      context: ./sample-next/my-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/myapp
    depends_on:
      - mongodb

  mongodb:
    image: mongo:7
    ports:
      - "27018:27017"  # Nutze einen anderen Port außen!
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
